export const FETCH_CLOTHES = "FETCH_CLOTHES";
export const FETCH_TECH = "FETCH_TECH";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCH_CURRENCIES = "FETCH_CURRENCIES";
export const SET_CURRENCY_VALUE = "SET_CURRENCY_VALUE";
export const COUNT_INCREASE = "COUNT_INCREASE";
export const COUNT_DECREASE = "COUNT_DECREASE";
